// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ServiciosFUMIT.Entities
{
    using System.Runtime.Serialization;

    // Clientes
    [Table("Clientes", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Cliente
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ClienteId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Cliente ID")]
        public int ClienteId { get; set; } // ClienteId (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SucursalId", Order = 2, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Sucursal ID")]
        public int SucursalId { get; set; } // SucursalId (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Clave", Order = 3, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(10)]
        [StringLength(10)]
        [Key]
        [Display(Name = "Clave")]
        public string Clave { get; set; } // Clave (Primary key) (length: 10)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Nombre", Order = 4, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(150)]
        [StringLength(150)]
        [Key]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (Primary key) (length: 150)

        [Column(@"SucursalCliente", Order = 5, TypeName = "varchar")]
        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "Sucursal cliente")]
        public string SucursalCliente { get; set; } // SucursalCliente (length: 80)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"RFC", Order = 6, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(13)]
        [StringLength(13)]
        [Key]
        [Display(Name = "Rfc")]
        public string Rfc { get; set; } // RFC (Primary key) (length: 13)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Direccion", Order = 7, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(150)]
        [StringLength(150)]
        [Key]
        [Display(Name = "Direccion")]
        public string Direccion { get; set; } // Direccion (Primary key) (length: 150)

        [Column(@"Ubicacion", Order = 8, TypeName = "varchar")]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Ubicacion")]
        public string Ubicacion { get; set; } // Ubicacion (length: 30)

        [Column(@"Contacto", Order = 9, TypeName = "varchar")]
        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "Contacto")]
        public string Contacto { get; set; } // Contacto (length: 80)

        [Column(@"Telefono", Order = 10, TypeName = "varchar")]
        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "Telefono")]
        public string Telefono { get; set; } // Telefono (length: 80)

        [Column(@"Correo", Order = 11, TypeName = "varchar")]
        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "Correo")]
        public string Correo { get; set; } // Correo (length: 80)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"FechaCreacion", Order = 12, TypeName = "datetime")]
        [Required]
        [Key]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha creacion")]
        public System.DateTime FechaCreacion { get; set; } // FechaCreacion (Primary key)

        [Column(@"Observaciones", Order = 13, TypeName = "varchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; } // Observaciones (length: 250)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Moroso", Order = 14, TypeName = "bit")]
        [Required]
        [Key]
        [Display(Name = "Moroso")]
        public bool Moroso { get; set; } // Moroso (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Bloqueado", Order = 15, TypeName = "bit")]
        [Required]
        [Key]
        [Display(Name = "Bloqueado")]
        public bool Bloqueado { get; set; } // Bloqueado (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Activo", Order = 16, TypeName = "bit")]
        [Required]
        [Key]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Borrado", Order = 17, TypeName = "bit")]
        [Required]
        [Key]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado (Primary key)

        public Cliente()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
