// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // AsignacionesEquipos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class AsignacionesequipoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Asignacionesequipo>
    {
        public AsignacionesequipoConfiguration()
            : this("dbo")
        {
        }

        public AsignacionesequipoConfiguration(string schema)
        {
            Property(x => x.FechaAsignación).IsOptional();
            Property(x => x.FechaEntrega).IsOptional();
            Property(x => x.FechaRegreso).IsOptional();

        }
    }

}
// </auto-generated>
