// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // AsignacionesEquipos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Asignacionesequipo: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Asignacion equipo ID")]
        [Key]
        public int AsignacionEquipoId { get; set; } // AsignacionEquipoId (Primary key)

        [Required]
        [Display(Name = "Equipo ID")]
        public int EquipoId { get; set; } // EquipoId

        [Required]
        [Display(Name = "Cliente ID")]
        public int ClienteId { get; set; } // ClienteId

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha asignaci n")]
        public System.DateTime? FechaAsignación { get; set; } // FechaAsignación

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha entrega")]
        public System.DateTime? FechaEntrega { get; set; } // FechaEntrega

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha regreso")]
        public System.DateTime? FechaRegreso { get; set; } // FechaRegreso

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        [MaxLength(120)]
        [StringLength(120)]
        [Display(Name = "Ubicacion")]
        public string Ubicacion { get; set; } // Ubicacion (length: 120)

        // Foreign keys

        /// <summary>
        /// Parent Clientes pointed by [AsignacionesEquipos].([ClienteId]) (FK_AsignacionesEquipos_Clientes)
        /// </summary>
        public virtual Cliente Clientes { get; set; } // FK_AsignacionesEquipos_Clientes

        /// <summary>
        /// Parent Equipo pointed by [AsignacionesEquipos].([EquipoId]) (FK_AsignacionesEquipos_Equipo)
        /// </summary>
        public virtual Equipo Equipo { get; set; } // FK_AsignacionesEquipos_Equipo

        public Asignacionesequipo()
        {
            Borrado = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
