// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // AsignacionesEquipos
    [Table("AsignacionesEquipos", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Asignacionesequipo: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"AsignacionEquipoId", Order = 1, TypeName = "int")]
        [Index(@"PK_AsignacionesEquipos", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Asignacion equipo ID")]
        public int AsignacionEquipoId { get; set; } // AsignacionEquipoId (Primary key)

        [Column(@"EquipoId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Equipo ID")]
        public int EquipoId { get; set; } // EquipoId

        [Column(@"ClienteId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Cliente ID")]
        public int ClienteId { get; set; } // ClienteId

        [Column(@"FechaAsignación", Order = 4, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha asignaci n")]
        public System.DateTime? FechaAsignación { get; set; } // FechaAsignación

        [Column(@"FechaEntrega", Order = 5, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha entrega")]
        public System.DateTime? FechaEntrega { get; set; } // FechaEntrega

        [Column(@"FechaRegreso", Order = 6, TypeName = "datetime")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha regreso")]
        public System.DateTime? FechaRegreso { get; set; } // FechaRegreso

        [Column(@"Borrado", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Foreign keys

        /// <summary>
        /// Parent Clientes pointed by [AsignacionesEquipos].([ClienteId]) (FK_AsignacionesEquipos_Clientes)
        /// </summary>
        [ForeignKey("ClienteId"), Required] public virtual Cliente Clientes { get; set; } // FK_AsignacionesEquipos_Clientes

        /// <summary>
        /// Parent Equipo pointed by [AsignacionesEquipos].([EquipoId]) (FK_AsignacionesEquipos_Equipo)
        /// </summary>
        [ForeignKey("EquipoId"), Required] public virtual Equipo Equipo { get; set; } // FK_AsignacionesEquipos_Equipo

        public Asignacionesequipo()
        {
            Borrado = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
