// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // CiclosFacturacion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class CiclosFacturacion: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Ciclo facturacion ID")]
        [Key]
        public int CicloFacturacionId { get; set; } // CicloFacturacionId (Primary key)

        [Required]
        [Display(Name = "Sucursal ID")]
        public int SucursalId { get; set; } // SucursalId

        [Required(AllowEmptyStrings = true)]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Dia")]
        public string Dia { get; set; } // Dia (length: 100)

        [Required]
        [Display(Name = "Semana")]
        public int Semana { get; set; } // Semana

        [Required]
        [Display(Name = "Mes")]
        public int Mes { get; set; } // Mes

        [Required]
        [Display(Name = "Por defecto")]
        public bool PorDefecto { get; set; } // PorDefecto

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child Ciclofacturacionclientes where [CicloFacturacionCliente].[CicloFacturacionId] point to this entity (FK_CicloFacturacionCliente_CicloFacturacionCliente)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CicloFacturacionCliente> Ciclofacturacionclientes { get; set; } // CicloFacturacionCliente.FK_CicloFacturacionCliente_CicloFacturacionCliente

        // Foreign keys

        /// <summary>
        /// Parent Sucursal pointed by [CiclosFacturacion].([SucursalId]) (FK_CiclosFacturacion_Sucursales)
        /// </summary>
        public virtual Sucursal Sucursal { get; set; } // FK_CiclosFacturacion_Sucursales

        public CiclosFacturacion()
        {
            Ciclofacturacionclientes = new System.Collections.Generic.List<CicloFacturacionCliente>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
