// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // CicloFacturacionCliente
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class CicloFacturacionCliente: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Ciclo facturacion cliente ID")]
        [Key]
        public int CicloFacturacionClienteId { get; set; } // CicloFacturacionClienteId (Primary key)

        [Required]
        [Display(Name = "Ciclo facturacion ID")]
        public int CicloFacturacionId { get; set; } // CicloFacturacionId

        [Required]
        [Display(Name = "Servicio ID")]
        public int ServicioId { get; set; } // ServicioId

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha inicio vigencia")]
        public System.DateTime? FechaInicioVigencia { get; set; } // FechaInicioVigencia

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha fin vigencia")]
        public System.DateTime? FechaFinVigencia { get; set; } // FechaFinVigencia

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Foreign keys

        /// <summary>
        /// Parent CiclosFacturacion pointed by [CicloFacturacionCliente].([CicloFacturacionId]) (FK_CicloFacturacionCliente_CicloFacturacionCliente)
        /// </summary>
        public virtual CiclosFacturacion CiclosFacturacion { get; set; } // FK_CicloFacturacionCliente_CicloFacturacionCliente

        public CicloFacturacionCliente()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
