// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.Runtime.Serialization;

    // CicloFacturacionCliente
    [Table("CicloFacturacionCliente", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class CicloFacturacionCliente
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"CicloFacturacionClienteId", Order = 1, TypeName = "int")]
        [Index(@"PK_CicloFacturacionCliente", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Ciclo facturacion cliente ID")]
        public int CicloFacturacionClienteId { get; set; } // CicloFacturacionClienteId (Primary key)

        [Column(@"CicloFacturacionId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Ciclo facturacion ID")]
        public int CicloFacturacionId { get; set; } // CicloFacturacionId

        [Column(@"ServicioId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Servicio ID")]
        public int ServicioId { get; set; } // ServicioId

        [Column(@"FechaInicioVigencia", Order = 4, TypeName = "datetime")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha inicio vigencia")]
        public System.DateTime FechaInicioVigencia { get; set; } // FechaInicioVigencia

        [Column(@"FechaFinVigencia", Order = 5, TypeName = "datetime")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha fin vigencia")]
        public System.DateTime FechaFinVigencia { get; set; } // FechaFinVigencia

        [Column(@"Activo", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Column(@"Borrado", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Foreign keys

        /// <summary>
        /// Parent CiclosFacturacion pointed by [CicloFacturacionCliente].([CicloFacturacionId]) (FK_CicloFacturacionCliente_CicloFacturacionCliente)
        /// </summary>
        [ForeignKey("CicloFacturacionId"), Required] public virtual CiclosFacturacion CiclosFacturacion { get; set; } // FK_CicloFacturacionCliente_CicloFacturacionCliente

        public CicloFacturacionCliente()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
