// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Clientes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Cliente: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Cliente ID")]
        [Key]
        public int ClienteId { get; set; } // ClienteId (Primary key)

        [Required]
        [Display(Name = "Sucursal ID")]
        public int SucursalId { get; set; } // SucursalId

        [MaxLength(10)]
        [StringLength(10)]
        [Display(Name = "Clave")]
        public string Clave { get; set; } // Clave (length: 10)

        [MaxLength(150)]
        [StringLength(150)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (length: 150)

        [MaxLength(180)]
        [StringLength(180)]
        [Display(Name = "Nombre fiscal")]
        public string NombreFiscal { get; set; } // NombreFiscal (length: 180)

        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "Sucursal cliente")]
        public string SucursalCliente { get; set; } // SucursalCliente (length: 80)

        [Required]
        [Display(Name = "Persona moral")]
        public bool PersonaMoral { get; set; } // PersonaMoral

        [MaxLength(13)]
        [StringLength(13)]
        [Display(Name = "Rfc")]
        public string Rfc { get; set; } // RFC (length: 13)

        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Direccion")]
        public string Direccion { get; set; } // Direccion (length: 250)

        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Direccion fiscal")]
        public string DireccionFiscal { get; set; } // DireccionFiscal (length: 250)

        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Ubicacion")]
        public string Ubicacion { get; set; } // Ubicacion (length: 30)

        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Contacto")]
        public string Contacto { get; set; } // Contacto (length: 300)

        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Telefono")]
        public string Telefono { get; set; } // Telefono (length: 300)

        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Correo")]
        public string Correo { get; set; } // Correo (length: 300)

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha creacion")]
        public System.DateTime? FechaCreacion { get; set; } // FechaCreacion

        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; } // Observaciones (length: 500)

        [Required]
        [Display(Name = "Requiere manifiesto")]
        public bool RequiereManifiesto { get; set; } // RequiereManifiesto

        [Required]
        [Display(Name = "Moroso")]
        public bool Moroso { get; set; } // Moroso

        [Required]
        [Display(Name = "Bloqueado")]
        public bool Bloqueado { get; set; } // Bloqueado

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Reverse navigation

        /// <summary>
        /// Child Asignacionesequipos where [AsignacionesEquipos].[ClienteId] point to this entity (FK_AsignacionesEquipos_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Asignacionesequipo> Asignacionesequipos { get; set; } // AsignacionesEquipos.FK_AsignacionesEquipos_Clientes
        /// <summary>
        /// Child Contactos where [Contactos].[ClienteId] point to this entity (FK_Contactos_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Contacto> Contactos { get; set; } // Contactos.FK_Contactos_Clientes
        /// <summary>
        /// Child Grupooperacionclientes where [GrupoOperacionClientes].[ClienteId] point to this entity (FK_GrupoOperacionClientes_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Grupooperacioncliente> Grupooperacionclientes { get; set; } // GrupoOperacionClientes.FK_GrupoOperacionClientes_Clientes
        /// <summary>
        /// Child Historialclientes where [HistorialCliente].[ClienteId] point to this entity (FK_HistorialCliente_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<HistorialCliente> Historialclientes { get; set; } // HistorialCliente.FK_HistorialCliente_Clientes
        /// <summary>
        /// Child Programacionserviciosclientes where [ProgramacionServiciosClientes].[ClienteId] point to this entity (FK_ProgramacionServiciosClientes_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Programacionservicioscliente> Programacionserviciosclientes { get; set; } // ProgramacionServiciosClientes.FK_ProgramacionServiciosClientes_Clientes
        /// <summary>
        /// Child Serviciosprogramados where [ServiciosProgramados].[ClienteId] point to this entity (FK_ServiciosProgramados_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Serviciosprogramado> Serviciosprogramados { get; set; } // ServiciosProgramados.FK_ServiciosProgramados_Clientes
        /// <summary>
        /// Child Tickets where [Tickets].[ClienteId] point to this entity (FK_Tickets_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Ticket> Tickets { get; set; } // Tickets.FK_Tickets_Clientes

        // Foreign keys

        /// <summary>
        /// Parent Sucursal pointed by [Clientes].([SucursalId]) (FK_Clientes_Sucursales)
        /// </summary>
        public virtual Sucursal Sucursal { get; set; } // FK_Clientes_Sucursales

        public Cliente()
        {
            PersonaMoral = false;
            FechaCreacion = System.DateTime.Now;
            RequiereManifiesto = false;
            Asignacionesequipos = new System.Collections.Generic.List<Asignacionesequipo>();
            Contactos = new System.Collections.Generic.List<Contacto>();
            Grupooperacionclientes = new System.Collections.Generic.List<Grupooperacioncliente>();
            Historialclientes = new System.Collections.Generic.List<HistorialCliente>();
            Programacionserviciosclientes = new System.Collections.Generic.List<Programacionservicioscliente>();
            Serviciosprogramados = new System.Collections.Generic.List<Serviciosprogramado>();
            Tickets = new System.Collections.Generic.List<Ticket>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
