// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Contactos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ContactoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Contacto>
    {
        public ContactoConfiguration()
            : this("dbo")
        {
        }

        public ContactoConfiguration(string schema)
        {
            Property(x => x.Nombre).IsUnicode(false);
            Property(x => x.Telefono).IsOptional().IsUnicode(false);
            Property(x => x.Correo).IsOptional().IsUnicode(false);
            Property(x => x.Tipo).IsOptional().IsUnicode(false);

        }
    }

}
// </auto-generated>
