// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // ContenedoresTickets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Contenedoresticket: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Contenedor ticket ID")]
        [Key]
        public int ContenedorTicketId { get; set; } // ContenedorTicketId (Primary key)

        [Required]
        [Display(Name = "Ticket ID")]
        public int TicketId { get; set; } // TicketId

        [Required]
        [Display(Name = "Contenedor ID")]
        public int ContenedorId { get; set; } // ContenedorId

        [Required]
        [Display(Name = "Levantes")]
        public int Levantes { get; set; } // Levantes

        // Foreign keys

        /// <summary>
        /// Parent Equipo pointed by [ContenedoresTickets].([ContenedorId]) (FK_ContenedoresTickets_Equipo)
        /// </summary>
        public virtual Equipo Equipo { get; set; } // FK_ContenedoresTickets_Equipo

        /// <summary>
        /// Parent Tickets pointed by [ContenedoresTickets].([TicketId]) (FK_ContenedoresTickets_Tickets)
        /// </summary>
        public virtual Ticket Tickets { get; set; } // FK_ContenedoresTickets_Tickets

        public Contenedoresticket()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
