// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // ContenedoresTickets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ContenedoresticketConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Contenedoresticket>
    {
        public ContenedoresticketConfiguration()
            : this("dbo")
        {
        }

        public ContenedoresticketConfiguration(string schema)
        {
            ToTable("ContenedoresTickets", schema);
            HasKey(x => x.ContenedorTicketId);

            Property(x => x.ContenedorTicketId).HasColumnName(@"ContenedorTicketId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TicketId).HasColumnName(@"TicketId").HasColumnType("int").IsRequired();
            Property(x => x.ContenedorId).HasColumnName(@"ContenedorId").HasColumnType("int").IsRequired();
            Property(x => x.Levantes).HasColumnName(@"Levantes").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Equipo).WithMany(b => b.Contenedorestickets).HasForeignKey(c => c.ContenedorId).WillCascadeOnDelete(false); // FK_ContenedoresTickets_Equipo
            HasRequired(a => a.Tickets).WithMany(b => b.Contenedorestickets).HasForeignKey(c => c.TicketId).WillCascadeOnDelete(false); // FK_ContenedoresTickets_Tickets
        }
    }

}
// </auto-generated>
