// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Contactos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Contacto: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Contacto ID")]
        [Key]
        public int ContactoId { get; set; } // ContactoId (Primary key)

        [Required]
        [Display(Name = "Cliente ID")]
        public int ClienteId { get; set; } // ClienteId

        [Required(AllowEmptyStrings = true)]
        [MaxLength(120)]
        [StringLength(120)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (length: 120)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Telefono")]
        public string Telefono { get; set; } // Telefono (length: 100)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Correo")]
        public string Correo { get; set; } // Correo (length: 100)

        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Tipo")]
        public string Tipo { get; set; } // Tipo (length: 20)

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Foreign keys

        /// <summary>
        /// Parent Clientes pointed by [Contactos].([ClienteId]) (FK_Contactos_Clientes)
        /// </summary>
        public virtual Cliente Clientes { get; set; } // FK_Contactos_Clientes

        public Contacto()
        {
            Borrado = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
