// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Equipo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Equipo: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Equipo ID")]
        [Key]
        public int EquipoId { get; set; } // EquipoId (Primary key)

        [Required]
        [Display(Name = "Tipo equipo ID")]
        public int TipoEquipoId { get; set; } // TipoEquipoId

        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Numero economico")]
        public string NumeroEconomico { get; set; } // NumeroEconomico (length: 15)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Estado")]
        public string Estado { get; set; } // Estado (length: 50)

        [Required]
        [Display(Name = "Requiere mantenimiento")]
        public bool RequiereMantenimiento { get; set; } // RequiereMantenimiento

        [Required]
        [Display(Name = "En mantenimiento")]
        public bool EnMantenimiento { get; set; } // EnMantenimiento

        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; } // Observaciones (length: 250)

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        [Required]
        [Display(Name = "Asignado")]
        public bool Asignado { get; set; } // Asignado

        // Reverse navigation

        /// <summary>
        /// Child Asignacionesequipos where [AsignacionesEquipos].[EquipoId] point to this entity (FK_AsignacionesEquipos_Equipo)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Asignacionesequipo> Asignacionesequipos { get; set; } // AsignacionesEquipos.FK_AsignacionesEquipos_Equipo
        /// <summary>
        /// Child Contenedorestickets where [ContenedoresTickets].[ContenedorId] point to this entity (FK_ContenedoresTickets_Equipo)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Contenedoresticket> Contenedorestickets { get; set; } // ContenedoresTickets.FK_ContenedoresTickets_Equipo
        /// <summary>
        /// Child Mantenimientosequipos where [MantenimientosEquipo].[EquipoId] point to this entity (FK_MantenimientosEquipo_Equipo)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MantenimientosEquipo> Mantenimientosequipos { get; set; } // MantenimientosEquipo.FK_MantenimientosEquipo_Equipo

        // Foreign keys

        /// <summary>
        /// Parent Tipoequipo pointed by [Equipo].([TipoEquipoId]) (FK_Equipo_TipoEquipos)
        /// </summary>
        public virtual Tipoequipo Tipoequipo { get; set; } // FK_Equipo_TipoEquipos

        public Equipo()
        {
            Activo = true;
            Borrado = false;
            Asignado = false;
            Asignacionesequipos = new System.Collections.Generic.List<Asignacionesequipo>();
            Contenedorestickets = new System.Collections.Generic.List<Contenedoresticket>();
            Mantenimientosequipos = new System.Collections.Generic.List<MantenimientosEquipo>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
