// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Equipo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class EquipoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Equipo>
    {
        public EquipoConfiguration()
            : this("dbo")
        {
        }

        public EquipoConfiguration(string schema)
        {
            Property(x => x.NumeroEconomico).IsOptional().IsUnicode(false);
            Property(x => x.Estado).IsUnicode(false);
            Property(x => x.Observaciones).IsOptional().IsUnicode(false);

        }
    }

}
// </auto-generated>
