// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Equipo
    [Table("Equipo", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Equipo: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"EquipoId", Order = 1, TypeName = "int")]
        [Index(@"PK_Equipo", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Equipo ID")]
        public int EquipoId { get; set; } // EquipoId (Primary key)

        [Column(@"TipoEquipoId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Tipo equipo ID")]
        public int TipoEquipoId { get; set; } // TipoEquipoId

        [Column(@"NumeroEconomico", Order = 3, TypeName = "varchar")]
        [MaxLength(15)]
        [StringLength(15)]
        [Display(Name = "Numero economico")]
        public string NumeroEconomico { get; set; } // NumeroEconomico (length: 15)

        [Column(@"Estado", Order = 4, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Estado")]
        public string Estado { get; set; } // Estado (length: 50)

        [Column(@"RequiereMantenimiento", Order = 5, TypeName = "bit")]
        [Required]
        [Display(Name = "Requiere mantenimiento")]
        public bool RequiereMantenimiento { get; set; } // RequiereMantenimiento

        [Column(@"EnMantenimiento", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "En mantenimiento")]
        public bool EnMantenimiento { get; set; } // EnMantenimiento

        [Column(@"Observaciones", Order = 7, TypeName = "varchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; } // Observaciones (length: 250)

        [Column(@"Activo", Order = 8, TypeName = "bit")]
        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Column(@"Borrado", Order = 9, TypeName = "bit")]
        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Reverse navigation

        /// <summary>
        /// Child Asignacionesequipos where [AsignacionesEquipos].[EquipoId] point to this entity (FK_AsignacionesEquipos_Equipo)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Asignacionesequipo> Asignacionesequipos { get; set; } // AsignacionesEquipos.FK_AsignacionesEquipos_Equipo

        // Foreign keys

        /// <summary>
        /// Parent Tipoequipo pointed by [Equipo].([TipoEquipoId]) (FK_Equipo_TipoEquipos)
        /// </summary>
        [ForeignKey("TipoEquipoId"), Required] public virtual Tipoequipo Tipoequipo { get; set; } // FK_Equipo_TipoEquipos

        public Equipo()
        {
            Activo = true;
            Borrado = false;
            Asignacionesequipos = new System.Collections.Generic.List<Asignacionesequipo>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
