// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Eventos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Evento: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Evento cliente ID")]
        [Key]
        public int EventoClienteId { get; set; } // EventoClienteId (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Codigo")]
        public string Codigo { get; set; } // Codigo (length: 5)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (length: 50)

        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; } // Descripcion (length: 250)

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        // Reverse navigation

        /// <summary>
        /// Child Historialclientes where [HistorialCliente].[EventoClienteId] point to this entity (FK_HistorialCliente_Eventos)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<HistorialCliente> Historialclientes { get; set; } // HistorialCliente.FK_HistorialCliente_Eventos

        public Evento()
        {
            Borrado = false;
            Activo = true;
            Historialclientes = new System.Collections.Generic.List<HistorialCliente>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
