// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // GrupoOperacionClientes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class GrupooperacionclienteConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Grupooperacioncliente>
    {
        public GrupooperacionclienteConfiguration()
            : this("dbo")
        {
        }

        public GrupooperacionclienteConfiguration(string schema)
        {
            ToTable("GrupoOperacionClientes", schema);
            HasKey(x => x.GrupoOperacionClienteId);

            Property(x => x.GrupoOperacionClienteId).HasColumnName(@"GrupoOperacionClienteId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.GrupoOperacionId).HasColumnName(@"GrupoOperacionId").HasColumnType("int").IsRequired();
            Property(x => x.ClienteId).HasColumnName(@"ClienteId").HasColumnType("int").IsRequired();
            Property(x => x.Orden).HasColumnName(@"Orden").HasColumnType("int").IsRequired();
            Property(x => x.Borrado).HasColumnName(@"Borrado").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Clientes).WithMany(b => b.Grupooperacionclientes).HasForeignKey(c => c.ClienteId).WillCascadeOnDelete(false); // FK_GrupoOperacionClientes_Clientes
            HasRequired(a => a.Gruposoperacion).WithMany(b => b.Grupooperacionclientes).HasForeignKey(c => c.GrupoOperacionId).WillCascadeOnDelete(false); // FK_GrupoOperacionClientes_GruposOperaciones
        }
    }

}
// </auto-generated>
