// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // GruposOperaciones
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class GruposoperacionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Gruposoperacion>
    {
        public GruposoperacionConfiguration()
            : this("dbo")
        {
        }

        public GruposoperacionConfiguration(string schema)
        {
            ToTable("GruposOperaciones", schema);
            HasKey(x => x.GrupoOperacionId);

            Property(x => x.GrupoOperacionId).HasColumnName(@"GrupoOperacionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Nombre).HasColumnName(@"Nombre").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(250);
            Property(x => x.ServicioId).HasColumnName(@"ServicioId").HasColumnType("int").IsRequired();
            Property(x => x.ServiciosDiarios).HasColumnName(@"ServiciosDiarios").HasColumnType("int").IsRequired();
            Property(x => x.Borrado).HasColumnName(@"Borrado").HasColumnType("bit").IsRequired();
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired();
            Property(x => x.InicioOperaciones).HasColumnName(@"InicioOperaciones").HasColumnType("datetime").IsRequired();
            Property(x => x.FinOperaciones).HasColumnName(@"FinOperaciones").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.Servicio).WithMany(b => b.Gruposoperaciones).HasForeignKey(c => c.ServicioId).WillCascadeOnDelete(false); // FK_GruposOperaciones_Servicios
        }
    }

}
// </auto-generated>
