// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // HistorialCliente
    [Table("HistorialCliente", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class HistorialCliente: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"HistorialClienteId", Order = 1, TypeName = "int")]
        [Index(@"PK_HistorialCliente", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Historial cliente ID")]
        public int HistorialClienteId { get; set; } // HistorialClienteId (Primary key)

        [Column(@"ClienteId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Cliente ID")]
        public int ClienteId { get; set; } // ClienteId

        [Column(@"EventoClienteId", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Evento cliente ID")]
        public int EventoClienteId { get; set; } // EventoClienteId

        [Column(@"Fecha", Order = 4, TypeName = "datetime")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha")]
        public System.DateTime Fecha { get; set; } // Fecha

        [Column(@"Observaciones", Order = 5, TypeName = "varchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; } // Observaciones (length: 250)

        [Column(@"Borrado", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Foreign keys

        /// <summary>
        /// Parent Clientes pointed by [HistorialCliente].([ClienteId]) (FK_HistorialCliente_Clientes)
        /// </summary>
        [ForeignKey("ClienteId"), Required] public virtual Clientes Clientes { get; set; } // FK_HistorialCliente_Clientes

        /// <summary>
        /// Parent Evento pointed by [HistorialCliente].([EventoClienteId]) (FK_HistorialCliente_Eventos)
        /// </summary>
        [ForeignKey("EventoClienteId"), Required] public virtual Evento Evento { get; set; } // FK_HistorialCliente_Eventos

        public HistorialCliente()
        {
            Borrado = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
