// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Mantenimientos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Mantenimiento: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Mantenimiento ID")]
        [Key]
        public int MantenimientoId { get; set; } // MantenimientoId (Primary key)

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha programada")]
        public System.DateTime? FechaProgramada { get; set; } // FechaProgramada

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha entrada mantenimiento")]
        public System.DateTime? FechaEntradaMantenimiento { get; set; } // FechaEntradaMantenimiento

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha salida mantenimiento")]
        public System.DateTime? FechaSalidaMantenimiento { get; set; } // FechaSalidaMantenimiento

        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; } // Observaciones (length: 250)

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        [Required]
        [Display(Name = "Realizado")]
        public bool Realizado { get; set; } // Realizado

        // Reverse navigation

        /// <summary>
        /// Child Mantenimientosequipos where [MantenimientosEquipo].[MantenimientoId] point to this entity (FK_MantenimientosEquipo_Mantenimientos)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MantenimientosEquipo> Mantenimientosequipos { get; set; } // MantenimientosEquipo.FK_MantenimientosEquipo_Mantenimientos

        public Mantenimiento()
        {
            Activo = true;
            Borrado = false;
            Realizado = false;
            Mantenimientosequipos = new System.Collections.Generic.List<MantenimientosEquipo>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
