// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // MantenimientosEquipo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class MantenimientosEquipo: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Mantenimiento equipo ID")]
        [Key]
        public int MantenimientoEquipoId { get; set; } // MantenimientoEquipoId (Primary key)

        [Required]
        [Display(Name = "Equipo ID")]
        public int EquipoId { get; set; } // EquipoId

        [Required]
        [Display(Name = "Mantenimiento ID")]
        public int MantenimientoId { get; set; } // MantenimientoId

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Foreign keys

        /// <summary>
        /// Parent Equipo pointed by [MantenimientosEquipo].([EquipoId]) (FK_MantenimientosEquipo_Equipo)
        /// </summary>
        public virtual Equipo Equipo { get; set; } // FK_MantenimientosEquipo_Equipo

        /// <summary>
        /// Parent Mantenimiento pointed by [MantenimientosEquipo].([MantenimientoId]) (FK_MantenimientosEquipo_Mantenimientos)
        /// </summary>
        public virtual Mantenimiento Mantenimiento { get; set; } // FK_MantenimientosEquipo_Mantenimientos

        public MantenimientosEquipo()
        {
            Borrado = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
