// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.Runtime.Serialization;

    // ProgramacionServicios
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ProgramacionservicioConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Programacionservicio>
    {
        public ProgramacionservicioConfiguration()
            : this("dbo")
        {
        }

        public ProgramacionservicioConfiguration(string schema)
        {
            Property(x => x.Nombre).IsOptional().IsUnicode(false);
            Property(x => x.Dias).IsOptional().IsUnicode(false);
            Property(x => x.Semana).IsOptional();
            Property(x => x.Mes).IsOptional();

        }
    }

}
// </auto-generated>
