// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // ProgramacionServicios
    [Table("ProgramacionServicios", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Programacionservicio: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ProgramacionServicioId", Order = 1, TypeName = "int")]
        [Index(@"PK_ProgramacionServicios", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Programacion servicio ID")]
        public int ProgramacionServicioId { get; set; } // ProgramacionServicioId (Primary key)

        [Column(@"SucursalId", Order = 2, TypeName = "int")]
        [Required]
        [Display(Name = "Sucursal ID")]
        public int SucursalId { get; set; } // SucursalId

        [Column(@"Nombre", Order = 3, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (length: 50)

        [Column(@"Dias", Order = 4, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Dias")]
        public string Dias { get; set; } // Dias (length: 50)

        [Column(@"Semana", Order = 5, TypeName = "int")]
        [Display(Name = "Semana")]
        public int? Semana { get; set; } // Semana

        [Column(@"Mes", Order = 6, TypeName = "int")]
        [Display(Name = "Mes")]
        public int? Mes { get; set; } // Mes

        // Reverse navigation

        /// <summary>
        /// Child Programacionserviciosclientes where [ProgramacionServiciosClientes].[ProgramacionServicioId] point to this entity (FK_ProgramacionServiciosClientes_ProgramacionServicios)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Programacionservicioscliente> Programacionserviciosclientes { get; set; } // ProgramacionServiciosClientes.FK_ProgramacionServiciosClientes_ProgramacionServicios

        // Foreign keys

        /// <summary>
        /// Parent Sucursal pointed by [ProgramacionServicios].([SucursalId]) (FK_ProgramacionServicios_Sucursales)
        /// </summary>
        [ForeignKey("SucursalId"), Required] public virtual Sucursal Sucursal { get; set; } // FK_ProgramacionServicios_Sucursales

        public Programacionservicio()
        {
            Programacionserviciosclientes = new System.Collections.Generic.List<Programacionservicioscliente>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
