// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // ProgramacionServiciosClientes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Programacionservicioscliente: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Programacion servicios cliente ID")]
        [Key]
        public int ProgramacionServiciosClienteId { get; set; } // ProgramacionServiciosClienteId (Primary key)

        [Required]
        [Display(Name = "Programacion servicio ID")]
        public int ProgramacionServicioId { get; set; } // ProgramacionServicioId

        [Required]
        [Display(Name = "Cliente ID")]
        public int ClienteId { get; set; } // ClienteId

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha inicio")]
        public System.DateTime FechaInicio { get; set; } // FechaInicio

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha termino")]
        public System.DateTime? FechaTermino { get; set; } // FechaTermino

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        [Required]
        [Display(Name = "Servicio ID")]
        public int ServicioId { get; set; } // ServicioId

        [Required]
        [Display(Name = "Servicios programados")]
        public bool ServiciosProgramados { get; set; } // ServiciosProgramados

        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "Area")]
        public string Area { get; set; } // Area (length: 80)

        // Reverse navigation

        /// <summary>
        /// Child Serviciosprogramados where [ServiciosProgramados].[ProgramacionServiciosClientesId] point to this entity (FK_ServiciosProgramados_ProgramacionServiciosClientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Serviciosprogramado> Serviciosprogramados { get; set; } // ServiciosProgramados.FK_ServiciosProgramados_ProgramacionServiciosClientes

        // Foreign keys

        /// <summary>
        /// Parent Clientes pointed by [ProgramacionServiciosClientes].([ClienteId]) (FK_ProgramacionServiciosClientes_Clientes)
        /// </summary>
        public virtual Cliente Clientes { get; set; } // FK_ProgramacionServiciosClientes_Clientes

        /// <summary>
        /// Parent Programacionservicio pointed by [ProgramacionServiciosClientes].([ProgramacionServicioId]) (FK_ProgramacionServiciosClientes_ProgramacionServicios)
        /// </summary>
        public virtual Programacionservicio Programacionservicio { get; set; } // FK_ProgramacionServiciosClientes_ProgramacionServicios

        /// <summary>
        /// Parent Servicio pointed by [ProgramacionServiciosClientes].([ServicioId]) (FK_ProgramacionServiciosClientes_Servicios)
        /// </summary>
        public virtual Servicio Servicio { get; set; } // FK_ProgramacionServiciosClientes_Servicios

        public Programacionservicioscliente()
        {
            FechaInicio = System.DateTime.Now;
            Activo = true;
            Borrado = false;
            ServiciosProgramados = false;
            Serviciosprogramados = new System.Collections.Generic.List<Serviciosprogramado>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
