// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // ProgramacionServicios
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Programacionservicio: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Programacion servicio ID")]
        [Key]
        public int ProgramacionServicioId { get; set; } // ProgramacionServicioId (Primary key)

        [Required]
        [Display(Name = "Sucursal ID")]
        public int SucursalId { get; set; } // SucursalId

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (length: 50)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Dias")]
        public string Dias { get; set; } // Dias (length: 50)

        [Display(Name = "Semana")]
        public int? Semana { get; set; } // Semana

        [Display(Name = "Mes")]
        public int? Mes { get; set; } // Mes

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Reverse navigation

        /// <summary>
        /// Child Programacionserviciosclientes where [ProgramacionServiciosClientes].[ProgramacionServicioId] point to this entity (FK_ProgramacionServiciosClientes_ProgramacionServicios)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Programacionservicioscliente> Programacionserviciosclientes { get; set; } // ProgramacionServiciosClientes.FK_ProgramacionServiciosClientes_ProgramacionServicios

        // Foreign keys

        /// <summary>
        /// Parent Sucursal pointed by [ProgramacionServicios].([SucursalId]) (FK_ProgramacionServicios_Sucursales)
        /// </summary>
        public virtual Sucursal Sucursal { get; set; } // FK_ProgramacionServicios_Sucursales

        public Programacionservicio()
        {
            Activo = true;
            Borrado = false;
            Programacionserviciosclientes = new System.Collections.Generic.List<Programacionservicioscliente>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
