// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Servicios
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Servicio: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Servicio ID")]
        [Key]
        public int ServicioId { get; set; } // ServicioId (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (length: 50)

        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; } // Descripcion (length: 250)

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Reverse navigation

        /// <summary>
        /// Child Programacionserviciosclientes where [ProgramacionServiciosClientes].[ServicioId] point to this entity (FK_ProgramacionServiciosClientes_Servicios)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Programacionservicioscliente> Programacionserviciosclientes { get; set; } // ProgramacionServiciosClientes.FK_ProgramacionServiciosClientes_Servicios
        /// <summary>
        /// Child Serviciosprogramados where [ServiciosProgramados].[ServicioId] point to this entity (FK_ServiciosProgramados_Servicios)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Serviciosprogramado> Serviciosprogramados { get; set; } // ServiciosProgramados.FK_ServiciosProgramados_Servicios
        /// <summary>
        /// Child Tickets where [Tickets].[ServicioId] point to this entity (FK_Tickets_Servicios)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Ticket> Tickets { get; set; } // Tickets.FK_Tickets_Servicios

        public Servicio()
        {
            Programacionserviciosclientes = new System.Collections.Generic.List<Programacionservicioscliente>();
            Serviciosprogramados = new System.Collections.Generic.List<Serviciosprogramado>();
            Tickets = new System.Collections.Generic.List<Ticket>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
