// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.Runtime.Serialization;

    // Sucursales
    [Table("Sucursales", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Sucursal
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"SuscursalId", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Suscursal ID")]
        public int SuscursalId { get; set; } // SuscursalId (Primary key)

        [Column(@"Numero", Order = 2, TypeName = "varchar")]
        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Numero")]
        public string Numero { get; set; } // Numero (length: 5)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Nombre", Order = 3, TypeName = "varchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (Primary key) (length: 50)

        [Column(@"Direccion", Order = 4, TypeName = "varchar")]
        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Direccion")]
        public string Direccion { get; set; } // Direccion (length: 250)

        [Column(@"Estado", Order = 5, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Estado")]
        public string Estado { get; set; } // Estado (length: 50)

        [Column(@"Ciudad", Order = 6, TypeName = "varchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Ciudad")]
        public string Ciudad { get; set; } // Ciudad (length: 50)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Activo", Order = 7, TypeName = "bit")]
        [Required]
        [Key]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo (Primary key)

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Borrado", Order = 8, TypeName = "bit")]
        [Required]
        [Key]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado (Primary key)

        public Sucursal()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
