// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // Sucursales
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Sucursal: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Sucursal ID")]
        [Key]
        public int SucursalId { get; set; } // SucursalId (Primary key)

        [MaxLength(5)]
        [StringLength(5)]
        [Display(Name = "Numero")]
        public string Numero { get; set; } // Numero (length: 5)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(120)]
        [StringLength(120)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (length: 120)

        [MaxLength(250)]
        [StringLength(250)]
        [Display(Name = "Direccion")]
        public string Direccion { get; set; } // Direccion (length: 250)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Estado")]
        public string Estado { get; set; } // Estado (length: 50)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Ciudad")]
        public string Ciudad { get; set; } // Ciudad (length: 50)

        [Required]
        [Display(Name = "Activo")]
        public bool Activo { get; set; } // Activo

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Reverse navigation

        /// <summary>
        /// Child Ciclosfacturaciones where [CiclosFacturacion].[SucursalId] point to this entity (FK_CiclosFacturacion_Sucursales)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CiclosFacturacion> Ciclosfacturaciones { get; set; } // CiclosFacturacion.FK_CiclosFacturacion_Sucursales
        /// <summary>
        /// Child Clientes where [Clientes].[SucursalId] point to this entity (FK_Clientes_Sucursales)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Cliente> Clientes { get; set; } // Clientes.FK_Clientes_Sucursales
        /// <summary>
        /// Child Operadores where [Operadores].[SucursalId] point to this entity (FK_Operadores_Sucursales)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Operador> Operadores { get; set; } // Operadores.FK_Operadores_Sucursales
        /// <summary>
        /// Child Programacionservicios where [ProgramacionServicios].[SucursalId] point to this entity (FK_ProgramacionServicios_Sucursales)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Programacionservicio> Programacionservicios { get; set; } // ProgramacionServicios.FK_ProgramacionServicios_Sucursales

        public Sucursal()
        {
            Activo = true;
            Borrado = false;
            Ciclosfacturaciones = new System.Collections.Generic.List<CiclosFacturacion>();
            Clientes = new System.Collections.Generic.List<Cliente>();
            Operadores = new System.Collections.Generic.List<Operador>();
            Programacionservicios = new System.Collections.Generic.List<Programacionservicio>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
