// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // TipoEquipos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Tipoequipo: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Tipo equipo ID")]
        [Key]
        public int TipoEquipoId { get; set; } // TipoEquipoId (Primary key)

        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; } // Nombre (length: 30)

        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; } // Descripcion (length: 100)

        [Required]
        [Display(Name = "Borrado")]
        public bool Borrado { get; set; } // Borrado

        // Reverse navigation

        /// <summary>
        /// Child Equipos where [Equipo].[TipoEquipoId] point to this entity (FK_Equipo_TipoEquipos)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Equipo> Equipos { get; set; } // Equipo.FK_Equipo_TipoEquipos

        public Tipoequipo()
        {
            Borrado = false;
            Equipos = new System.Collections.Generic.List<Equipo>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
