// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class UspCalendarioSemanalServiciosReturnModel
    {
        public System.DateTime? FechaServicio { get; set; }
        public System.String DiaSemana { get; set; }
        public System.Int32 ClienteId { get; set; }
        public System.String NombreCliente { get; set; }
        public System.String NombreProgramacion { get; set; }
        public System.Int32 ProgramacionServicioId { get; set; }
        public System.Int32 ProgramacionServiciosClienteId { get; set; }
        public System.Int32 ServicioId { get; set; }
        public System.String NombreServicio { get; set; }
        public System.Int32? ServicioProgramadoId { get; set; }
        public System.Boolean? Cancelado { get; set; }
        public System.Int32? Prioridad { get; set; }
    }

}
// </auto-generated>
