// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace FUMIT.Entidades
{
    using System.ComponentModel;
    using System.Runtime.Serialization;

    // vsProgramacionServiciosClientes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Vsprogramacionservicioscliente: INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;


        [Required]
        [Display(Name = "Programacion servicios cliente ID")]
        [Key]
        public int ProgramacionServiciosClienteId { get; set; } // ProgramacionServiciosClienteId (Primary key)

        [Required]
        [Display(Name = "Programacion servicio ID")]
        [Key]
        public int ProgramacionServicioId { get; set; } // ProgramacionServicioId (Primary key)

        [Required]
        [Display(Name = "Cliente ID")]
        [Key]
        public int ClienteId { get; set; } // ClienteId (Primary key)

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha inicio")]
        [Key]
        public System.DateTime FechaInicio { get; set; } // FechaInicio (Primary key)

        [DataType(DataType.DateTime)]
        [Display(Name = "Fecha termino")]
        public System.DateTime? FechaTermino { get; set; } // FechaTermino

        [Required]
        [Display(Name = "Activo")]
        [Key]
        public bool Activo { get; set; } // Activo (Primary key)

        [Required]
        [Display(Name = "Borrado")]
        [Key]
        public bool Borrado { get; set; } // Borrado (Primary key)

        [Required]
        [Display(Name = "Servicio ID")]
        [Key]
        public int ServicioId { get; set; } // ServicioId (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Nombre")]
        [Key]
        public string Nombre { get; set; } // Nombre (Primary key) (length: 50)

        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Nombre horario programado")]
        public string NombreHorarioProgramado { get; set; } // NombreHorarioProgramado (length: 50)

        [MaxLength(80)]
        [StringLength(80)]
        [Display(Name = "Area")]
        public string Area { get; set; } // Area (length: 80)

        public Vsprogramacionservicioscliente()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
