// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // Activos$
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Activos36Configuration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Activos36>
    {
        public Activos36Configuration()
            : this("dbo")
        {
        }

        public Activos36Configuration(string schema)
        {
            ToTable("Activos$", schema);
            HasKey(x => x.Activoid);

            Property(x => x.F1).HasColumnName(@"F1").HasColumnType("float").IsOptional();
            Property(x => x.Columna4).HasColumnName(@"Columna4").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.NombreFiscal).HasColumnName(@"NOMBRE FISCAL").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.NombreComercial).HasColumnName(@"NOMBRE COMERCIAL").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Rfc).HasColumnName(@"RFC").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.FechaDeIngreso).HasColumnName(@"FECHA DE INGRESO").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Contenedor3M).HasColumnName(@"CONTENEDOR 3m").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Contenedor6M).HasColumnName(@"CONTENEDOR 6m").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.TarifaAct2016).HasColumnName(@"TARIFA ACT 2016").HasColumnType("float").IsOptional();
            Property(x => x.Frecuencia).HasColumnName(@"FRECUENCIA").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Contacto).HasColumnName(@"CONTACTO").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Telefono).HasColumnName(@"TELEFONO").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.EMail).HasColumnName(@"E-MAIL").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.DireccionDeServicio).HasColumnName(@"DIRECCION DE SERVICIO").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.DiasYHorariosDeRecoleccion).HasColumnName(@"DIAS Y HORARIOS DE RECOLECCION").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.DiasDeRevision).HasColumnName(@"DIAS DE REVISION").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.HorarioDeRevision).HasColumnName(@"HORARIO DE REVISION").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.ContactoDePagos).HasColumnName(@"CONTACTO DE PAGOS").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.CorreoDePagos).HasColumnName(@"CORREO DE PAGOS").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.DiasDePago).HasColumnName(@"DIAS DE PAGO").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.HorarioDePagos).HasColumnName(@"HORARIO DE PAGOS").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Columna1).HasColumnName(@"Columna1").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Columna12).HasColumnName(@"Columna12").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.ModoDePago).HasColumnName(@"MODO DE PAGO").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Activoid).HasColumnName(@"activoid").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
        }
    }

}
// </auto-generated>
