// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // Activos$
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Activos36
    {
        public double? F1 { get; set; } // F1
        public string Columna4 { get; set; } // Columna4 (length: 255)
        public string NombreFiscal { get; set; } // NOMBRE FISCAL (length: 255)
        public string NombreComercial { get; set; } // NOMBRE COMERCIAL (length: 255)
        public string Rfc { get; set; } // RFC (length: 255)
        public string FechaDeIngreso { get; set; } // FECHA DE INGRESO (length: 255)
        public string Contenedor3M { get; set; } // CONTENEDOR 3m (length: 255)
        public string Contenedor6M { get; set; } // CONTENEDOR 6m (length: 255)
        public double? TarifaAct2016 { get; set; } // TARIFA ACT 2016
        public string Frecuencia { get; set; } // FRECUENCIA (length: 255)
        public string Contacto { get; set; } // CONTACTO (length: 255)
        public string Telefono { get; set; } // TELEFONO (length: 255)
        public string EMail { get; set; } // E-MAIL (length: 255)
        public string DireccionDeServicio { get; set; } // DIRECCION DE SERVICIO (length: 255)
        public string DiasYHorariosDeRecoleccion { get; set; } // DIAS Y HORARIOS DE RECOLECCION (length: 255)
        public string DiasDeRevision { get; set; } // DIAS DE REVISION (length: 255)
        public string HorarioDeRevision { get; set; } // HORARIO DE REVISION (length: 255)
        public string ContactoDePagos { get; set; } // CONTACTO DE PAGOS (length: 255)
        public string CorreoDePagos { get; set; } // CORREO DE PAGOS (length: 255)
        public string DiasDePago { get; set; } // DIAS DE PAGO (length: 255)
        public string HorarioDePagos { get; set; } // HORARIO DE PAGOS (length: 255)
        public string Columna1 { get; set; } // Columna1 (length: 255)
        public string Columna12 { get; set; } // Columna12 (length: 255)
        public string ModoDePago { get; set; } // MODO DE PAGO (length: 255)
        public int Activoid { get; set; } // activoid (Primary key)
    }

}
// </auto-generated>
