// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // AsignacionesEquipos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class AsignacionesEquipos
    {
        public int AsignacionEquipoId { get; set; } // AsignacionEquipoId (Primary key)
        public int EquipoId { get; set; } // EquipoId
        public int ClienteId { get; set; } // ClienteId
        public System.DateTime? FechaAsignación { get; set; } // FechaAsignación
        public System.DateTime? FechaEntrega { get; set; } // FechaEntrega
        public System.DateTime? FechaRegreso { get; set; } // FechaRegreso
        public bool Borrado { get; set; } // Borrado
        public string Ubicacion { get; set; } // Ubicacion (length: 120)

        // Foreign keys

        /// <summary>
        /// Parent Cliente pointed by [AsignacionesEquipos].([ClienteId]) (FK_AsignacionesEquipos_Clientes)
        /// </summary>
        public virtual Cliente Cliente { get; set; } // FK_AsignacionesEquipos_Clientes

        /// <summary>
        /// Parent Equipo pointed by [AsignacionesEquipos].([EquipoId]) (FK_AsignacionesEquipos_Equipo)
        /// </summary>
        public virtual Equipo Equipo { get; set; } // FK_AsignacionesEquipos_Equipo

        public AsignacionesEquipos()
        {
            Borrado = false;
        }
    }

}
// </auto-generated>
