// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // CiclosFacturacion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CiclosFacturacion
    {
        public int CicloFacturacionId { get; set; } // CicloFacturacionId (Primary key)
        public int SucursalId { get; set; } // SucursalId
        public string Dia { get; set; } // Dia (length: 100)
        public int Semana { get; set; } // Semana
        public int Mes { get; set; } // Mes
        public bool PorDefecto { get; set; } // PorDefecto
        public bool Activo { get; set; } // Activo
        public bool Borrado { get; set; } // Borrado
        public string Nombre { get; set; } // Nombre (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child CicloFacturacionClientes where [CicloFacturacionCliente].[CicloFacturacionId] point to this entity (FK_CicloFacturacionCliente_CicloFacturacionCliente)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<CicloFacturacionCliente> CicloFacturacionClientes { get; set; } // CicloFacturacionCliente.FK_CicloFacturacionCliente_CicloFacturacionCliente

        // Foreign keys

        /// <summary>
        /// Parent Sucursale pointed by [CiclosFacturacion].([SucursalId]) (FK_CiclosFacturacion_Sucursales)
        /// </summary>
        public virtual Sucursale Sucursale { get; set; } // FK_CiclosFacturacion_Sucursales

        public CiclosFacturacion()
        {
            CicloFacturacionClientes = new System.Collections.Generic.List<CicloFacturacionCliente>();
        }
    }

}
// </auto-generated>
