// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // CiclosFacturacion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CiclosFacturacionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CiclosFacturacion>
    {
        public CiclosFacturacionConfiguration()
            : this("dbo")
        {
        }

        public CiclosFacturacionConfiguration(string schema)
        {
            ToTable("CiclosFacturacion", schema);
            HasKey(x => x.CicloFacturacionId);

            Property(x => x.CicloFacturacionId).HasColumnName(@"CicloFacturacionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SucursalId).HasColumnName(@"SucursalId").HasColumnType("int").IsRequired();
            Property(x => x.Dia).HasColumnName(@"Dia").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.Semana).HasColumnName(@"Semana").HasColumnType("int").IsRequired();
            Property(x => x.Mes).HasColumnName(@"Mes").HasColumnType("int").IsRequired();
            Property(x => x.PorDefecto).HasColumnName(@"PorDefecto").HasColumnType("bit").IsRequired();
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired();
            Property(x => x.Borrado).HasColumnName(@"Borrado").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Sucursale).WithMany(b => b.CiclosFacturacions).HasForeignKey(c => c.SucursalId).WillCascadeOnDelete(false); // FK_CiclosFacturacion_Sucursales
        }
    }

}
// </auto-generated>
