// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // CicloFacturacionCliente
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CicloFacturacionClienteConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CicloFacturacionCliente>
    {
        public CicloFacturacionClienteConfiguration()
            : this("dbo")
        {
        }

        public CicloFacturacionClienteConfiguration(string schema)
        {
            ToTable("CicloFacturacionCliente", schema);
            HasKey(x => x.CicloFacturacionClienteId);

            Property(x => x.CicloFacturacionClienteId).HasColumnName(@"CicloFacturacionClienteId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.CicloFacturacionId).HasColumnName(@"CicloFacturacionId").HasColumnType("int").IsRequired();
            Property(x => x.ServicioId).HasColumnName(@"ServicioId").HasColumnType("int").IsRequired();
            Property(x => x.FechaInicioVigencia).HasColumnName(@"FechaInicioVigencia").HasColumnType("datetime").IsRequired();
            Property(x => x.FechaFinVigencia).HasColumnName(@"FechaFinVigencia").HasColumnType("datetime").IsRequired();
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired();
            Property(x => x.Borrado).HasColumnName(@"Borrado").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.CiclosFacturacion).WithMany(b => b.CicloFacturacionClientes).HasForeignKey(c => c.CicloFacturacionId).WillCascadeOnDelete(false); // FK_CicloFacturacionCliente_CicloFacturacionCliente
        }
    }

}
// </auto-generated>
