// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // CicloFacturacionCliente
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class CicloFacturacionCliente
    {
        public int CicloFacturacionClienteId { get; set; } // CicloFacturacionClienteId (Primary key)
        public int CicloFacturacionId { get; set; } // CicloFacturacionId
        public int ServicioId { get; set; } // ServicioId
        public System.DateTime? FechaInicioVigencia { get; set; } // FechaInicioVigencia
        public System.DateTime? FechaFinVigencia { get; set; } // FechaFinVigencia
        public bool Activo { get; set; } // Activo
        public bool Borrado { get; set; } // Borrado

        // Foreign keys

        /// <summary>
        /// Parent CiclosFacturacion pointed by [CicloFacturacionCliente].([CicloFacturacionId]) (FK_CicloFacturacionCliente_CicloFacturacionCliente)
        /// </summary>
        public virtual CiclosFacturacion CiclosFacturacion { get; set; } // FK_CicloFacturacionCliente_CicloFacturacionCliente
    }

}
// </auto-generated>
