// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // Clientes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Cliente
    {
        public int ClienteId { get; set; } // ClienteId (Primary key)
        public int SucursalId { get; set; } // SucursalId
        public string Clave { get; set; } // Clave (length: 10)
        public string Nombre { get; set; } // Nombre (length: 150)
        public string NombreFiscal { get; set; } // NombreFiscal (length: 180)
        public string SucursalCliente { get; set; } // SucursalCliente (length: 80)
        public bool PersonaMoral { get; set; } // PersonaMoral
        public string Rfc { get; set; } // RFC (length: 13)
        public string Direccion { get; set; } // Direccion (length: 250)
        public string DireccionFiscal { get; set; } // DireccionFiscal (length: 250)
        public string Ubicacion { get; set; } // Ubicacion (length: 30)
        public string Contacto { get; set; } // Contacto (length: 300)
        public string Telefono { get; set; } // Telefono (length: 300)
        public string Correo { get; set; } // Correo (length: 300)
        public System.DateTime? FechaCreacion { get; set; } // FechaCreacion
        public string Observaciones { get; set; } // Observaciones (length: 500)
        public bool RequiereManifiesto { get; set; } // RequiereManifiesto
        public bool Moroso { get; set; } // Moroso
        public bool Bloqueado { get; set; } // Bloqueado
        public bool Activo { get; set; } // Activo
        public bool Borrado { get; set; } // Borrado

        // Reverse navigation

        /// <summary>
        /// Child Contactoes where [Contactos].[ClienteId] point to this entity (FK_Contactos_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Contacto> Contactoes { get; set; } // Contactos.FK_Contactos_Clientes
        /// <summary>
        /// Child HistorialClientes where [HistorialCliente].[ClienteId] point to this entity (FK_HistorialCliente_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<HistorialCliente> HistorialClientes { get; set; } // HistorialCliente.FK_HistorialCliente_Clientes
        /// <summary>
        /// Child ProgramacionServiciosClientes where [ProgramacionServiciosClientes].[ClienteId] point to this entity (FK_ProgramacionServiciosClientes_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ProgramacionServiciosCliente> ProgramacionServiciosClientes { get; set; } // ProgramacionServiciosClientes.FK_ProgramacionServiciosClientes_Clientes
        /// <summary>
        /// Child ServiciosProgramadoes where [ServiciosProgramados].[ClienteId] point to this entity (FK_ServiciosProgramados_Clientes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ServiciosProgramado> ServiciosProgramadoes { get; set; } // ServiciosProgramados.FK_ServiciosProgramados_Clientes

        // Foreign keys

        /// <summary>
        /// Parent Sucursale pointed by [Clientes].([SucursalId]) (FK_Clientes_Sucursales)
        /// </summary>
        public virtual Sucursale Sucursale { get; set; } // FK_Clientes_Sucursales

        public Cliente()
        {
            PersonaMoral = false;
            FechaCreacion = System.DateTime.Now;
            RequiereManifiesto = false;
            Contactoes = new System.Collections.Generic.List<Contacto>();
            HistorialClientes = new System.Collections.Generic.List<HistorialCliente>();
            ProgramacionServiciosClientes = new System.Collections.Generic.List<ProgramacionServiciosCliente>();
            ServiciosProgramadoes = new System.Collections.Generic.List<ServiciosProgramado>();
        }
    }

}
// </auto-generated>
