// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // Contactos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Contacto
    {
        public int ContactoId { get; set; } // ContactoId (Primary key)
        public int ClienteId { get; set; } // ClienteId
        public string Nombre { get; set; } // Nombre (length: 120)
        public string Telefono { get; set; } // Telefono (length: 100)
        public string Correo { get; set; } // Correo (length: 100)
        public string Tipo { get; set; } // Tipo (length: 20)

        // Foreign keys

        /// <summary>
        /// Parent Cliente pointed by [Contactos].([ClienteId]) (FK_Contactos_Clientes)
        /// </summary>
        public virtual Cliente Cliente { get; set; } // FK_Contactos_Clientes
    }

}
// </auto-generated>
