// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // Equipo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class EquipoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Equipo>
    {
        public EquipoConfiguration()
            : this("dbo")
        {
        }

        public EquipoConfiguration(string schema)
        {
            ToTable("Equipo", schema);
            HasKey(x => x.EquipoId);

            Property(x => x.EquipoId).HasColumnName(@"EquipoId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TipoEquipoId).HasColumnName(@"TipoEquipoId").HasColumnType("int").IsRequired();
            Property(x => x.NumeroEconomico).HasColumnName(@"NumeroEconomico").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(15);
            Property(x => x.Estado).HasColumnName(@"Estado").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.RequiereMantenimiento).HasColumnName(@"RequiereMantenimiento").HasColumnType("bit").IsRequired();
            Property(x => x.EnMantenimiento).HasColumnName(@"EnMantenimiento").HasColumnType("bit").IsRequired();
            Property(x => x.Observaciones).HasColumnName(@"Observaciones").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(250);
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired();
            Property(x => x.Borrado).HasColumnName(@"Borrado").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.TipoEquipos).WithMany(b => b.Equipoes).HasForeignKey(c => c.TipoEquipoId).WillCascadeOnDelete(false); // FK_Equipo_TipoEquipos
        }
    }

}
// </auto-generated>
