// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // Equipo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Equipo
    {
        public int EquipoId { get; set; } // EquipoId (Primary key)
        public int TipoEquipoId { get; set; } // TipoEquipoId
        public string NumeroEconomico { get; set; } // NumeroEconomico (length: 15)
        public string Estado { get; set; } // Estado (length: 50)
        public bool RequiereMantenimiento { get; set; } // RequiereMantenimiento
        public bool EnMantenimiento { get; set; } // EnMantenimiento
        public string Observaciones { get; set; } // Observaciones (length: 250)
        public bool Activo { get; set; } // Activo
        public bool Borrado { get; set; } // Borrado
        public bool Asignado { get; set; } // Asignado

        // Reverse navigation

        /// <summary>
        /// Child AsignacionesEquipos where [AsignacionesEquipos].[EquipoId] point to this entity (FK_AsignacionesEquipos_Equipo)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AsignacionesEquipos> AsignacionesEquipos { get; set; } // AsignacionesEquipos.FK_AsignacionesEquipos_Equipo
        /// <summary>
        /// Child MantenimientosEquipoes where [MantenimientosEquipo].[EquipoId] point to this entity (FK_MantenimientosEquipo_Equipo)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MantenimientosEquipo> MantenimientosEquipoes { get; set; } // MantenimientosEquipo.FK_MantenimientosEquipo_Equipo

        // Foreign keys

        /// <summary>
        /// Parent TipoEquipos pointed by [Equipo].([TipoEquipoId]) (FK_Equipo_TipoEquipos)
        /// </summary>
        public virtual TipoEquipos TipoEquipos { get; set; } // FK_Equipo_TipoEquipos

        public Equipo()
        {
            Activo = true;
            Borrado = false;
            Asignado = false;
            AsignacionesEquipos = new System.Collections.Generic.List<AsignacionesEquipos>();
            MantenimientosEquipoes = new System.Collections.Generic.List<MantenimientosEquipo>();
        }
    }

}
// </auto-generated>
