// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // Eventos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Evento
    {
        public int EventoClienteId { get; set; } // EventoClienteId (Primary key)
        public string Codigo { get; set; } // Codigo (length: 5)
        public string Nombre { get; set; } // Nombre (length: 50)
        public string Descripcion { get; set; } // Descripcion (length: 250)
        public bool Borrado { get; set; } // Borrado
        public bool Activo { get; set; } // Activo

        // Reverse navigation

        /// <summary>
        /// Child HistorialClientes where [HistorialCliente].[EventoClienteId] point to this entity (FK_HistorialCliente_Eventos)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<HistorialCliente> HistorialClientes { get; set; } // HistorialCliente.FK_HistorialCliente_Eventos

        public Evento()
        {
            Borrado = false;
            Activo = true;
            HistorialClientes = new System.Collections.Generic.List<HistorialCliente>();
        }
    }

}
// </auto-generated>
