// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // HistorialCliente
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class HistorialCliente
    {
        public int HistorialClienteId { get; set; } // HistorialClienteId (Primary key)
        public int ClienteId { get; set; } // ClienteId
        public int EventoClienteId { get; set; } // EventoClienteId
        public System.DateTime Fecha { get; set; } // Fecha
        public string Observaciones { get; set; } // Observaciones (length: 250)

        // Foreign keys

        /// <summary>
        /// Parent Cliente pointed by [HistorialCliente].([ClienteId]) (FK_HistorialCliente_Clientes)
        /// </summary>
        public virtual Cliente Cliente { get; set; } // FK_HistorialCliente_Clientes

        /// <summary>
        /// Parent Evento pointed by [HistorialCliente].([EventoClienteId]) (FK_HistorialCliente_Eventos)
        /// </summary>
        public virtual Evento Evento { get; set; } // FK_HistorialCliente_Eventos
    }

}
// </auto-generated>
