// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    public interface IFumitContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Activos36> Activos36 { get; set; } // Activos$
        System.Data.Entity.DbSet<AsignacionesEquipos> AsignacionesEquipos { get; set; } // AsignacionesEquipos
        System.Data.Entity.DbSet<CicloFacturacionCliente> CicloFacturacionClientes { get; set; } // CicloFacturacionCliente
        System.Data.Entity.DbSet<CiclosFacturacion> CiclosFacturacions { get; set; } // CiclosFacturacion
        System.Data.Entity.DbSet<Cliente> Clientes { get; set; } // Clientes
        System.Data.Entity.DbSet<Contacto> Contactoes { get; set; } // Contactos
        System.Data.Entity.DbSet<Equipo> Equipoes { get; set; } // Equipo
        System.Data.Entity.DbSet<Evento> Eventoes { get; set; } // Eventos
        System.Data.Entity.DbSet<HistorialCliente> HistorialClientes { get; set; } // HistorialCliente
        System.Data.Entity.DbSet<ProgramacionServicio> ProgramacionServicios { get; set; } // ProgramacionServicios
        System.Data.Entity.DbSet<ProgramacionServiciosCliente> ProgramacionServiciosClientes { get; set; } // ProgramacionServiciosClientes
        System.Data.Entity.DbSet<Servicio> Servicios { get; set; } // Servicios
        System.Data.Entity.DbSet<ServiciosProgramado> ServiciosProgramadoes { get; set; } // ServiciosProgramados
        System.Data.Entity.DbSet<ServiciosSucursale> ServiciosSucursales { get; set; } // ServiciosSucursales
        System.Data.Entity.DbSet<Sucursale> Sucursales { get; set; } // Sucursales
        System.Data.Entity.DbSet<TipoEquipos> TipoEquipos { get; set; } // TipoEquipos

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
