// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // MantenimientosEquipo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class MantenimientosEquipoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MantenimientosEquipo>
    {
        public MantenimientosEquipoConfiguration()
            : this("dbo")
        {
        }

        public MantenimientosEquipoConfiguration(string schema)
        {
            ToTable("MantenimientosEquipo", schema);
            HasKey(x => x.MantenimientoEquipoId);

            Property(x => x.MantenimientoEquipoId).HasColumnName(@"MantenimientoEquipoId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EquipoId).HasColumnName(@"EquipoId").HasColumnType("int").IsRequired();
            Property(x => x.MantenimientoId).HasColumnName(@"MantenimientoId").HasColumnType("int").IsRequired();
            Property(x => x.Borrado).HasColumnName(@"Borrado").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Equipo).WithMany(b => b.MantenimientosEquipoes).HasForeignKey(c => c.EquipoId).WillCascadeOnDelete(false); // FK_MantenimientosEquipo_Equipo
            HasRequired(a => a.Mantenimiento).WithMany(b => b.MantenimientosEquipoes).HasForeignKey(c => c.MantenimientoId).WillCascadeOnDelete(false); // FK_MantenimientosEquipo_Mantenimientos
        }
    }

}
// </auto-generated>
