// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // MantenimientosEquipo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class MantenimientosEquipo
    {
        public int MantenimientoEquipoId { get; set; } // MantenimientoEquipoId (Primary key)
        public int EquipoId { get; set; } // EquipoId
        public int MantenimientoId { get; set; } // MantenimientoId
        public bool Borrado { get; set; } // Borrado

        // Foreign keys

        /// <summary>
        /// Parent Equipo pointed by [MantenimientosEquipo].([EquipoId]) (FK_MantenimientosEquipo_Equipo)
        /// </summary>
        public virtual Equipo Equipo { get; set; } // FK_MantenimientosEquipo_Equipo

        /// <summary>
        /// Parent Mantenimiento pointed by [MantenimientosEquipo].([MantenimientoId]) (FK_MantenimientosEquipo_Mantenimientos)
        /// </summary>
        public virtual Mantenimiento Mantenimiento { get; set; } // FK_MantenimientosEquipo_Mantenimientos

        public MantenimientosEquipo()
        {
            Borrado = false;
        }
    }

}
// </auto-generated>
