// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // Mantenimientos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Mantenimiento
    {
        public int MantenimientoId { get; set; } // MantenimientoId (Primary key)
        public System.DateTime? FechaProgramada { get; set; } // FechaProgramada
        public System.DateTime? FechaEntradaMantenimiento { get; set; } // FechaEntradaMantenimiento
        public System.DateTime? FechaSalidaMantenimiento { get; set; } // FechaSalidaMantenimiento
        public string Observaciones { get; set; } // Observaciones (length: 250)
        public bool Activo { get; set; } // Activo
        public bool Borrado { get; set; } // Borrado
        public bool Realizado { get; set; } // Realizado

        // Reverse navigation

        /// <summary>
        /// Child MantenimientosEquipoes where [MantenimientosEquipo].[MantenimientoId] point to this entity (FK_MantenimientosEquipo_Mantenimientos)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MantenimientosEquipo> MantenimientosEquipoes { get; set; } // MantenimientosEquipo.FK_MantenimientosEquipo_Mantenimientos

        public Mantenimiento()
        {
            Activo = true;
            Borrado = false;
            Realizado = false;
            MantenimientosEquipoes = new System.Collections.Generic.List<MantenimientosEquipo>();
        }
    }

}
// </auto-generated>
