// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // ProgramacionServicios
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ProgramacionServicio
    {
        public int ProgramacionServicioId { get; set; } // ProgramacionServicioId (Primary key)
        public int SucursalId { get; set; } // SucursalId
        public string Nombre { get; set; } // Nombre (length: 50)
        public string Dias { get; set; } // Dias (length: 50)
        public int? Semana { get; set; } // Semana
        public int? Mes { get; set; } // Mes

        // Reverse navigation

        /// <summary>
        /// Child ProgramacionServiciosClientes where [ProgramacionServiciosClientes].[ProgramacionServicioId] point to this entity (FK_ProgramacionServiciosClientes_ProgramacionServicios)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ProgramacionServiciosCliente> ProgramacionServiciosClientes { get; set; } // ProgramacionServiciosClientes.FK_ProgramacionServiciosClientes_ProgramacionServicios

        // Foreign keys

        /// <summary>
        /// Parent Sucursale pointed by [ProgramacionServicios].([SucursalId]) (FK_ProgramacionServicios_Sucursales)
        /// </summary>
        public virtual Sucursale Sucursale { get; set; } // FK_ProgramacionServicios_Sucursales

        public ProgramacionServicio()
        {
            ProgramacionServiciosClientes = new System.Collections.Generic.List<ProgramacionServiciosCliente>();
        }
    }

}
// </auto-generated>
