// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // ProgramacionServicios
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ProgramacionServicioConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ProgramacionServicio>
    {
        public ProgramacionServicioConfiguration()
            : this("dbo")
        {
        }

        public ProgramacionServicioConfiguration(string schema)
        {
            ToTable("ProgramacionServicios", schema);
            HasKey(x => x.ProgramacionServicioId);

            Property(x => x.ProgramacionServicioId).HasColumnName(@"ProgramacionServicioId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SucursalId).HasColumnName(@"SucursalId").HasColumnType("int").IsRequired();
            Property(x => x.Nombre).HasColumnName(@"Nombre").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Dias).HasColumnName(@"Dias").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Semana).HasColumnName(@"Semana").HasColumnType("int").IsOptional();
            Property(x => x.Mes).HasColumnName(@"Mes").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.Sucursale).WithMany(b => b.ProgramacionServicios).HasForeignKey(c => c.SucursalId).WillCascadeOnDelete(false); // FK_ProgramacionServicios_Sucursales
        }
    }

}
// </auto-generated>
