// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // ServiciosSucursales
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ServiciosSucursale
    {
        public int ServicioSucursalId { get; set; } // ServicioSucursalId (Primary key)
        public int SucursalId { get; set; } // SucursalId
        public int ServicioId { get; set; } // ServicioId
        public bool Borrado { get; set; } // Borrado
        public bool Activo { get; set; } // Activo

        public ServiciosSucursale()
        {
            Borrado = false;
            Activo = true;
        }
    }

}
// </auto-generated>
