// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // Servicios
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Servicio
    {
        public int ServicioId { get; set; } // ServicioId (Primary key)
        public string Nombre { get; set; } // Nombre (length: 50)
        public string Descripcion { get; set; } // Descripcion (length: 250)
        public bool Activo { get; set; } // Activo
        public bool Borrado { get; set; } // Borrado

        // Reverse navigation

        /// <summary>
        /// Child ProgramacionServiciosClientes where [ProgramacionServiciosClientes].[ServicioId] point to this entity (FK_ProgramacionServiciosClientes_Servicios)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ProgramacionServiciosCliente> ProgramacionServiciosClientes { get; set; } // ProgramacionServiciosClientes.FK_ProgramacionServiciosClientes_Servicios
        /// <summary>
        /// Child ServiciosProgramadoes where [ServiciosProgramados].[ServicioId] point to this entity (FK_ServiciosProgramados_Servicios)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ServiciosProgramado> ServiciosProgramadoes { get; set; } // ServiciosProgramados.FK_ServiciosProgramados_Servicios

        public Servicio()
        {
            ProgramacionServiciosClientes = new System.Collections.Generic.List<ProgramacionServiciosCliente>();
            ServiciosProgramadoes = new System.Collections.Generic.List<ServiciosProgramado>();
        }
    }

}
// </auto-generated>
