// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // ServiciosProgramados
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ServiciosProgramado
    {
        public int ServicioProgramadoId { get; set; } // ServicioProgramadoId (Primary key)
        public int ClienteId { get; set; } // ClienteId
        public int ServicioId { get; set; } // ServicioId
        public System.DateTime FechaServicio { get; set; } // FechaServicio
        public string Tipo { get; set; } // Tipo (length: 50)
        public bool Cancelado { get; set; } // Cancelado
        public bool Borrado { get; set; } // Borrado
        public bool Activo { get; set; } // Activo
        public int Prioridad { get; set; } // Prioridad
        public string Observaciones { get; set; } // Observaciones (length: 250)

        // Foreign keys

        /// <summary>
        /// Parent Cliente pointed by [ServiciosProgramados].([ClienteId]) (FK_ServiciosProgramados_Clientes)
        /// </summary>
        public virtual Cliente Cliente { get; set; } // FK_ServiciosProgramados_Clientes

        /// <summary>
        /// Parent Servicio pointed by [ServiciosProgramados].([ServicioId]) (FK_ServiciosProgramados_Servicios)
        /// </summary>
        public virtual Servicio Servicio { get; set; } // FK_ServiciosProgramados_Servicios

        public ServiciosProgramado()
        {
            Cancelado = false;
            Borrado = false;
            Activo = true;
            Prioridad = 1000;
        }
    }

}
// </auto-generated>
