// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Exportador_FUMIT
{

    // TipoEquipos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TipoEquipos
    {
        public int TipoEquipoId { get; set; } // TipoEquipoId (Primary key)
        public string Nombre { get; set; } // Nombre (length: 30)
        public string Descripcion { get; set; } // Descripcion (length: 100)
        public bool Borrado { get; set; } // Borrado

        // Reverse navigation

        /// <summary>
        /// Child Equipoes where [Equipo].[TipoEquipoId] point to this entity (FK_Equipo_TipoEquipos)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Equipo> Equipoes { get; set; } // Equipo.FK_Equipo_TipoEquipos

        public TipoEquipos()
        {
            Borrado = false;
            Equipoes = new System.Collections.Generic.List<Equipo>();
        }
    }

}
// </auto-generated>
